name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generates the contribution graph SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: Soumik-Coder18
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Push the generated SVG to the output branch
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}